apiVersion: v1
kind: Service
metadata:
  name: fullstack
  labels:
    app: fullstack
spec:
  ports:
    - port: 80
  selector:
    app: fullstack
  type: LoadBalancer	
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack
  labels:
    app: fullstack
spec:
  selector:
    matchLabels:
      app: fullstack
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fullstack
    spec:
      containers:
      - image: braveior/braveior.fullstack:v2.0
        name: fullstack
        ports:
        - containerPort: 80
          name: fullstack