apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  ports:
    - name: http-80
      port: 8080
      targetPort: 80
  selector:
    app: phpmyadmin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: PMA_HOST
              value: mysql-db
          name: phpmyadmin
          image: 'docker.io/phpmyadmin/phpmyadmin:latest'
          ports:
            - containerPort: 80
